# Generated by Django 5.0.2 on 2025-05-27 07:11

from django.db import migrations
import uuid

def generate_id_numbers(apps, schema_editor):
    UserProfile = apps.get_model('accounts', 'UserProfile')
    for profile in UserProfile.objects.all():
        if not profile.id_number:
            profile.id_number = f"EMP{uuid.uuid4().hex[:6].upper()}"
            profile.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_id_number_userprofile_salary'),
    ]

    operations = [
        migrations.RunPython(generate_id_numbers),
    ]
