# Generated by Django 5.0.2 on 2025-05-28 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_personaldata'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata',
            name='civil_service_eligibility',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personaldata',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personaldata',
            name='training_programs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personaldata',
            name='voluntary_work',
            field=models.TextField(blank=True, null=True),
        ),
    ]
