# Generated by Django 5.0.2 on 2025-05-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_personaldata_civil_service_eligibility_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaldata',
            old_name='occupation',
            new_name='eligibility_place',
        ),
        migrations.RenameField(
            model_name='personaldata',
            old_name='training_programs',
            new_name='employer_address',
        ),
        migrations.RemoveField(
            model_name='personaldata',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='personaldata',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='personaldata',
            name='eligibility_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personaldata',
            name='eligibility_license',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='personaldata',
            name='eligibility_rating',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='personaldata',
            name='employer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personaldata',
            name='employment_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personaldata',
            name='employment_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personaldata',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personaldata',
            name='monthly_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='personaldata',
            name='position_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personaldata',
            name='salary_grade',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='civil_service_eligibility',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='education_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='emergency_contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('W', 'Widowed')], max_length=20, null=True),
        ),
    ]
