# Generated by Django 5.0.2 on 2025-05-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_userprofile_age_remove_userprofile_is_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personaldata',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
